# Welcome to Jekyll!
#

# Site settings
title: Eve Corp
description: |
  software.that.evolves
owner: Eve # or company name
first_published: 2017 # if migrating another site, the year of your first publish
email: info@eve-corp.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://http://www.eve-corp.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/eve-corp
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: info@eve-corp.com
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
